### ISSUE TITLE
SkinChangeEvent and SkinChangedEvent are synchronous but are triggered asynchronously

### ISSUE THREAD

**Issue by Iaiao** [Nan1t/Custom-Skins-Manager#3]
/skin player \<name\>
`java.lang.IllegalStateException: SkinChangeEvent may only be triggered synchronously.`

**Comment by Nan1t** [comment]
Yes, sorry. There is dev version in main branch, i forgot to create a separate one ¯\_(ツ)_/¯. In release it will be changed anyway.
